{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xm.lua_annotation",
    "module": "lua_annotation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lua_annotation-1.0.0.jar",
          "url": "lua_annotation-1.0.0.jar",
          "size": 1441,
          "sha512": "b9682516e38ea7a0ce86d296e5b36a36cb4b36807bed577967fa2b6676789eb88e490974a3ad64c18d7def3c98e3fcd14fdb3a87615188a79daad01a4c97fa63",
          "sha256": "d34bb289811ccbbfdb34192fd0c52cf8b2320c0c65e4a09540efb807ac8cc403",
          "sha1": "975afb56fb630e4dc784edc77130f52b2c395018",
          "md5": "ae9d1a37ebb12a1e21a38ea103166339"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lua_annotation-1.0.0.jar",
          "url": "lua_annotation-1.0.0.jar",
          "size": 1441,
          "sha512": "b9682516e38ea7a0ce86d296e5b36a36cb4b36807bed577967fa2b6676789eb88e490974a3ad64c18d7def3c98e3fcd14fdb3a87615188a79daad01a4c97fa63",
          "sha256": "d34bb289811ccbbfdb34192fd0c52cf8b2320c0c65e4a09540efb807ac8cc403",
          "sha1": "975afb56fb630e4dc784edc77130f52b2c395018",
          "md5": "ae9d1a37ebb12a1e21a38ea103166339"
        }
      ]
    }
  ]
}
