{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xm.lua_apt",
    "module": "lua_apt",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lua_apt-1.0.0.jar",
          "url": "lua_apt-1.0.0.jar",
          "size": 3858,
          "sha512": "a29346ea2d3d48b92c41f0d78a5917c4a12f0bef8bf7754a43c6c1aa05728c5d286a63b8299f62768a22855a104b22ac0f3f3f5dbd98c6e298ca714c0e8a6377",
          "sha256": "54673b5361c633ce28d4371e775dfa8fc81e79cda98d4f36cebd06ab02f5e619",
          "sha1": "257d7efa08854b528d3f5daccb608b8ff83b939c",
          "md5": "e691e192ede5a0c45925c67a3370dac6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.xm.lua_annotation",
          "module": "lua_annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lua_apt-1.0.0.jar",
          "url": "lua_apt-1.0.0.jar",
          "size": 3858,
          "sha512": "a29346ea2d3d48b92c41f0d78a5917c4a12f0bef8bf7754a43c6c1aa05728c5d286a63b8299f62768a22855a104b22ac0f3f3f5dbd98c6e298ca714c0e8a6377",
          "sha256": "54673b5361c633ce28d4371e775dfa8fc81e79cda98d4f36cebd06ab02f5e619",
          "sha1": "257d7efa08854b528d3f5daccb608b8ff83b939c",
          "md5": "e691e192ede5a0c45925c67a3370dac6"
        }
      ]
    }
  ]
}
