{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xm.luajava",
    "module": "lua_java",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lua_java-1.0.0.aar",
          "url": "lua_java-1.0.0.aar",
          "size": 494387,
          "sha512": "fda4fce4c97a50c98b4199ce74b09ec27fe12332841a3063c3d4e16fc209e370aa4738a888dac8053ee0b5f435dad5aaf6d84ea1c9e5631698ae151f70213eb2",
          "sha256": "3728377da6efa347f8d4f7190a75a27a755df19a4bfc63c022dfdb9eab4ab177",
          "sha1": "59e92a9dd3a91b6ba8ddba006e0d3ea6274fa71b",
          "md5": "299fe1837069e6cd915fe5278b677006"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lua_java-1.0.0.aar",
          "url": "lua_java-1.0.0.aar",
          "size": 494387,
          "sha512": "fda4fce4c97a50c98b4199ce74b09ec27fe12332841a3063c3d4e16fc209e370aa4738a888dac8053ee0b5f435dad5aaf6d84ea1c9e5631698ae151f70213eb2",
          "sha256": "3728377da6efa347f8d4f7190a75a27a755df19a4bfc63c022dfdb9eab4ab177",
          "sha1": "59e92a9dd3a91b6ba8ddba006e0d3ea6274fa71b",
          "md5": "299fe1837069e6cd915fe5278b677006"
        }
      ]
    }
  ]
}
