{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xm.luajava",
    "module": "lua_java",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lua_java-1.0.0.aar",
          "url": "lua_java-1.0.0.aar",
          "size": 494240,
          "sha512": "f8f5f62383581e4a0283d1e3b0e80204592dab0209ee94732e196eda22624da9aff3dcd8753fd1a6169daa8df2674a25233b1fd2596604f3f123b21c000b4a23",
          "sha256": "848a1caf1fc5ac060de7db28c5e397191a8c93bca81a2385ac9e71bc9b3770a5",
          "sha1": "7e19963ff3dc0b8c5f0e23fdb2914358d1e45651",
          "md5": "61c62397c4008f6fdcde99cfe164e234"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lua_java-1.0.0.aar",
          "url": "lua_java-1.0.0.aar",
          "size": 494240,
          "sha512": "f8f5f62383581e4a0283d1e3b0e80204592dab0209ee94732e196eda22624da9aff3dcd8753fd1a6169daa8df2674a25233b1fd2596604f3f123b21c000b4a23",
          "sha256": "848a1caf1fc5ac060de7db28c5e397191a8c93bca81a2385ac9e71bc9b3770a5",
          "sha1": "7e19963ff3dc0b8c5f0e23fdb2914358d1e45651",
          "md5": "61c62397c4008f6fdcde99cfe164e234"
        }
      ]
    }
  ]
}
